name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: npm ci
      - run: npm run build
      - name: Release
        env:
          GIT_AUTHOR_NAME: "Shantanu Verma"
          GIT_AUTHOR_EMAIL: "vermashantanu@hotmail.com"
        run: npx semantic-release