on:
  push:
    branches: [main, tests]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Start Redis Single Node
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Start Redis Cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with: 
          master1-port: 6380
          master2-port: 6381
          master3-port: 6382
          slave1-port: 6383
          slave2-port: 6384
          slave3-port: 6385

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test